---
- name: Run shut-oracle script on oracledb hosts group
  hosts: oracledb
  gather_facts: false  

  tasks:
    - name: Run shut-oracle.sh script
      shell: /etc/ansible/scripts/shut-oracle.sh  # Script location on host
      become: true  # Run as root?
